// This file was autogenerated by closure-primitives/depswriter.py.
// Please do not edit.
goog.addDependency('.././src/closure-primitives/base.js', ['goog'], []);
goog.addDependency('.././src/define/typedarray/hybrid.js', ['USE_TYPEDARRAY'], []);
goog.addDependency('.././src/define/typedarray/use.js', ['USE_TYPEDARRAY'], []);
goog.addDependency('.././src/src/adler32.js', ['Zlib.Adler32'], []);
goog.addDependency('.././src/src/bitstream.js', ['Zlib.BitStream'], []);
goog.addDependency('.././src/src/deflate.js', ['Zlib.Deflate'], ['Zlib.Adler32', 'Zlib.BitStream', 'Zlib.RawDeflate', 'Zlib.Util']);
goog.addDependency('.././src/src/heap.js', ['Zlib.Heap'], []);
goog.addDependency('.././src/src/inflate.js', ['Zlib.Inflate'], ['Zlib.Adler32']);
goog.addDependency('.././src/src/rawdeflate.js', ['Zlib.RawDeflate'], ['Zlib.BitStream', 'Zlib.Heap', 'Zlib.Util']);
goog.addDependency('.././src/src/util.js', ['Zlib.Util'], []);
goog.addDependency('.././src/src/zlib.js', ['Zlib'], ['Zlib.Deflate', 'Zlib.Inflate']);
