// This file was autogenerated by closure-primitives/depswriter.py.
// Please do not edit.
goog.addDependency('../closure-primitives/base.js', ['goog'], []);
goog.addDependency('../define/typedarray/hybrid.js', ['USE_TYPEDARRAY'], []);
goog.addDependency('../define/typedarray/use.js', ['USE_TYPEDARRAY'], []);
goog.addDependency('../src/adler32.js', ['Zlib.Adler32'], ['Zlib.Util']);
goog.addDependency('../src/bitstream.js', ['Zlib.BitStream'], []);
goog.addDependency('../src/crc32.js', ['Zlib.CRC32'], []);
goog.addDependency('../src/deflate.js', ['Zlib.Deflate'], ['Zlib.Adler32', 'Zlib.RawDeflate']);
goog.addDependency('../src/export_object.js', ['Zlib.exportObject'], []);
goog.addDependency('../src/gunzip.js', ['Zlib.Gunzip'], ['Zlib.CRC32', 'Zlib.GunzipMember', 'Zlib.Gzip', 'Zlib.RawInflate']);
goog.addDependency('../src/gunzip_member.js', ['Zlib.GunzipMember'], []);
goog.addDependency('../src/gzip.js', ['Zlib.Gzip'], ['Zlib.CRC32', 'Zlib.RawDeflate']);
goog.addDependency('../src/heap.js', ['Zlib.Heap'], []);
goog.addDependency('../src/huffman.js', ['Zlib.Huffman'], []);
goog.addDependency('../src/inflate.js', ['Zlib.Inflate'], ['Zlib.Adler32', 'Zlib.RawInflate']);
goog.addDependency('../src/inflate_stream.js', ['Zlib.InflateStream'], ['Zlib.RawInflateStream']);
goog.addDependency('../src/rawdeflate.js', ['Zlib.RawDeflate'], ['Zlib.BitStream', 'Zlib.Heap']);
goog.addDependency('../src/rawinflate.js', ['Zlib.RawInflate'], ['Zlib.Huffman']);
goog.addDependency('../src/rawinflate_stream.js', ['Zlib.RawInflateStream'], ['Zlib.Huffman']);
goog.addDependency('../src/unzip.js', ['Zlib.Unzip'], ['Zlib.CRC32', 'Zlib.RawInflate', 'Zlib.Zip']);
goog.addDependency('../src/util.js', ['Zlib.Util'], []);
goog.addDependency('../src/zip.js', ['Zlib.Zip'], ['Zlib.CRC32', 'Zlib.RawDeflate']);
goog.addDependency('../src/zlib.js', ['Zlib'], ['Zlib.Deflate', 'Zlib.Inflate']);
